overblog_graphql:
  definitions:
    schema:
      query: RootQuery
      mutation: RootMutation
      types: [OnlineServiceFeature, OnlineService]
    mappings:
      types:
      - type: attribute
        dir: "%atoolo_citygov.src_dir%/Service/GraphQL/Types"
        suffix: ~
      - type: attribute
        dir: "%atoolo_citygov.src_dir%/Service/GraphQL/Query"
        suffix: ~
      - type: attribute
        dir: "%atoolo_citygov.src_dir%/Service/GraphQL/Input"
        suffix: ~
      - types: [yaml]
        dir: "%atoolo_citygov.config_dir%/graphql/types"
        suffix: ~